# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loueatsville', '0002_auto_20170225_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('date', models.DateField()),
                ('type', models.CharField(max_length=20)),
                ('buisness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loueatsville.Buisness')),
            ],
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('buisness', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loueatsville.Buisness')),
            ],
        ),
    ]
