# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loueatsville', '0003_inspection_violation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buisness',
            new_name='Business',
        ),
        migrations.RenameField(
            model_name='inspection',
            old_name='buisness',
            new_name='business',
        ),
        migrations.RenameField(
            model_name='violation',
            old_name='buisness',
            new_name='business',
        ),
    ]
