# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 20:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loueatsville', '0005_auto_20170319_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='violation',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
