# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-01 00:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loueatsville', '0007_auto_20170319_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='score',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='type',
            field=models.CharField(choices=[('FOLLOWUP', 'Follow Up'), ('REGULAR', 'Regular')], max_length=20),
        ),
        migrations.AlterField(
            model_name='violation',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='loueatsville.Business'),
        ),
    ]
